"""case model and failure taxonomy

Revision ID: 058aa00395e7
Revises: 5563f5bb69f0
Create Date: 2026-09-01 02:26:42.853845
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '058aa00395e7'
down_revision: str | None = '5563f5bb69f0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('razorpay_order_id', sa.String(length=64), nullable=False),
    sa.Column('razorpay_payment_id', sa.String(length=64), nullable=False),
    sa.Column('customer_email', sa.String(length=320), nullable=True),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('is_mandate', sa.Boolean(), nullable=False),
    sa.Column('failure_class', sa.String(length=32), nullable=False),
    sa.Column('failure_reason_raw', sa.String(length=128), nullable=True),
    sa.Column('arm', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempts_used', sa.Integer(), nullable=False),
    sa.Column('messages_sent', sa.Integer(), nullable=False),
    sa.Column('last_contact_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pre_debit_notice_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discount_offered', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cases')),
    sa.UniqueConstraint('razorpay_order_id', name=op.f('uq_cases_razorpay_order_id'))
    )
    op.create_index(op.f('ix_cases_arm'), 'cases', ['arm'], unique=False)
    op.create_index(op.f('ix_cases_failure_class'), 'cases', ['failure_class'], unique=False)
    op.create_index(op.f('ix_cases_status'), 'cases', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cases_status'), table_name='cases')
    op.drop_index(op.f('ix_cases_failure_class'), table_name='cases')
    op.drop_index(op.f('ix_cases_arm'), table_name='cases')
    op.drop_table('cases')
    # ### end Alembic commands ###
