"""outcomes table

Revision ID: 5461527e8fbe
Revises: 058aa00395e7
Create Date: 2026-09-01 23:43:52.795280
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "5461527e8fbe"
down_revision: str | None = "058aa00395e7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outcomes",
        sa.Column("case_id", sa.String(length=36), nullable=False),
        sa.Column("recovered_amount_paise", sa.BigInteger(), nullable=False),
        sa.Column("recovered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("via", sa.String(length=16), nullable=False),
        sa.Column("arm_at_recovery", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], name=op.f("fk_outcomes_case_id_cases")),
        sa.PrimaryKeyConstraint("case_id", name=op.f("pk_outcomes")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("outcomes")
    # ### end Alembic commands ###
