"""case escalation columns

Revision ID: 23fb567c4bee
Revises: 5461527e8fbe
Create Date: 2026-09-02 01:21:31.737966
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "23fb567c4bee"
down_revision: str | None = "5461527e8fbe"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cases", sa.Column("escalated_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("cases", sa.Column("escalation_rule_id", sa.String(length=64), nullable=True))
    op.add_column("cases", sa.Column("escalation_reason", sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cases", "escalation_reason")
    op.drop_column("cases", "escalation_rule_id")
    op.drop_column("cases", "escalated_at")
    # ### end Alembic commands ###
