"""action completed executors

Revision ID: dd5ec244182e
Revises: c40a5c800c5e
Create Date: 2026-09-04 19:46:18.015687
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "dd5ec244182e"
down_revision: str | None = "c40a5c800c5e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "actions",
        sa.Column("completed_executors", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("actions", "completed_executors")
    # ### end Alembic commands ###
