"""actions table and case diagnosis marker

Revision ID: f7a9bd14f590
Revises: 23fb567c4bee
Create Date: 2026-09-02 02:10:07.237507
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "f7a9bd14f590"
down_revision: str | None = "23fb567c4bee"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "actions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("case_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("verdict_rule_id", sa.String(length=64), nullable=False),
        sa.Column("scheduled_for", sa.DateTime(timezone=True), nullable=False),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("dispatch_attempts", sa.Integer(), nullable=False),
        sa.Column("result", sa.Boolean(), nullable=True),
        sa.Column("error", sa.String(length=512), nullable=True),
        sa.Column("razorpay_ref", sa.String(length=64), nullable=True),
        sa.Column("payload_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], name=op.f("fk_actions_case_id_cases")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_actions")),
    )
    op.create_index(op.f("ix_actions_case_id"), "actions", ["case_id"], unique=False)
    op.create_index(
        "ix_actions_poller_claim",
        "actions",
        ["scheduled_for", "executed_at", "claimed_at"],
        unique=False,
    )
    op.add_column(
        "cases", sa.Column("last_diagnosed_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cases", "last_diagnosed_at")
    op.drop_index("ix_actions_poller_claim", table_name="actions")
    op.drop_index(op.f("ix_actions_case_id"), table_name="actions")
    op.drop_table("actions")
    # ### end Alembic commands ###
